name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # daily at midnight UTC
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: stalomeow/metrics@projects-v2
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, maintainer, deployer, developer,
            scripter, packager, influencer, contributor
          plugin_languages: yes
          plugin_languages_ignored: >-
            dockerfile, cmake
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_repositories: yes
          plugin_repositories_featured: lambypy/SolarSystemGravitation
